### ISSUE TITLE
Adding Kafka Consumer Producer as a Default for Template

### ISSUE THREAD

**Issue by dendisuhubdy** [bitwyre/template-python#1]
Would like to discuss if we can define our services with a default of having both
- [x] Kafka consumer
- [x] Kafka producer

**Comment by nevrending** [comment]
I disagree since not all of our services requires Kafka

**Comment by dendisuhubdy** [comment]
I see

**Comment by dendisuhubdy** [comment]
I thought that we might as well put it in and for all `async` operations, but if not we can just remove it from the created repo

**Comment by nevrending** [comment]
That might be more convenient but people can forget to remove it
